services:
  wordpress:
    image: wordpress
    container_name: ${PROJECT_NAME}_wordpress # Nombre único del contenedor
    restart: always
    # ports:
    #   - "${WORDPRESS_PORT}:80" # Usa variable de entorno
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./volumes/site:/var/www/html
      - ./plugins/simulador:/var/www/html/wp-content/plugins/simulador
      - ./volumes/config/php/conf.d/custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini # Añadir solo un archivo
  db:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db # Nombre único del contenedor
    restart: always
    command: --lower_case_table_names=1
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    volumes:
      - ./volumes/db/:/var/lib/mysql # Datos de la base de datos